global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['10.0.0.6:9100']

  - job_name: 'backend'
    static_configs:
      - targets: ['10.0.0.6:3001']
    metrics_path: '/api/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['10.0.0.6:9121']
